---
title: "PNAD Contínua" # Título do relatório
subtitle: "**Dia da Mulher**"
author: "Fernanda Kelly R. Silva | www.fernandakellyrs.com"
lang: pt 
date: "`r format(Sys.Date())`" 
date-format: short 
toc: true 
format: 
    html: 
      embed-resources: true
      #css: ["custom.css"] 
      code-fold: false 
      code-tools: true  
      theme: 
        light: cosmo
        dark: superhero 
#title-block-banner: "#874a9c" 
code-annotations: hover 
execute:
  warning: false
  message: false
  echo: false
---

```{r}
options(timeout = 600) 
options(scipen = 999)
```

```{r}
#| echo: false
#| 
# install.packages("PNADcIBGE")
# install.packages("survey")
library(PNADcIBGE)
library(survey)
library(foreign)
library(srvyr)
library(reactable)
library(purrr)
library(janitor)
library(gtsummary)
```


# Demanda: Dia da Mulher

```{r}
load(file = "C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Trimestre/dadosPNADc2024_completo.RData")

load(file = "C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Trimestre/dadosPNADc2025_completo.RData")
```

```{r}
dadosPNADc2025_DM <- dadosPNADc2025_completo %>% 
    dplyr::filter(UF == "Rio Grande do Sul")

dadosPNADc2025_DM_srv  <- PNADcIBGE::pnadc_design(dadosPNADc2025_DM)
dadosPNADc2025_DM_srv  <- srvyr::as_survey(dadosPNADc2025_DM_srv)
```

### Perfil

```{r}
# 
# table_perfil <-
#   dadosPNADc2025_DM_srv %>% 
#   #dplyr::select(V2005, V2010, V1022, V2007) %>% 
#   gtsummary::tbl_svysummary(
#     percent = "row",
#     include = c(V2010, V1022, V2007),
#     by = V2007
#   )
# 
# table_perfil <-
#   dadosPNADc2025_DM_srv %>% 
#   dplyr::group_by(V2005, V2010) %>% 
#   dplyr::summarise(freq = srvyr::survey_total(vartype = c("se", "ci", "var", "cv")))
# 
# table_perfil %>% 
#   gt::gt()

```

```{r}
 table_perfil_1 <-
   dadosPNADc2025_DM_srv %>% 
   #dplyr::select(V2005, V2010, V1022, V2007) %>% 
  dplyr::group_by(V2007) %>% 
  dplyr::summarise(freq =  srvyr::survey_total(vartype = c("cv"))  ) %>% 
  gt::gt() 

table_perfil_1
```

```{r}
 table_perfil_4 <-
   dadosPNADc2025_DM_srv %>% 
  dplyr::group_by(V2007, V1022) %>% 
  dplyr::summarise(freq =  srvyr::survey_total(vartype = c("cv"))  ) %>% 
  gt::gt() %>%
  gt::tab_spanner(
    label = "Homem",
    columns = starts_with("Homem")
  ) %>%
  gt::tab_spanner(
    label = "Mulher",
    columns = starts_with("Mulher")
  ) %>% 
  gt::cols_label(
    V1022 = "Situação do domicílio"
  )

table_perfil_4
  #gt::gt( row_group_as_column = TRUE)
```

```{r}
 table_perfil_2 <-
   dadosPNADc2025_DM_srv %>% 
  dplyr::group_by(V2007, V2005) %>% 
  dplyr::summarise(freq =  srvyr::survey_total(vartype = c("cv"))  ) %>% 
  gt::gt() %>%
  gt::tab_spanner(
    label = "Homem",
    columns = starts_with("Homem")
  ) %>%
  gt::tab_spanner(
    label = "Mulher",
    columns = starts_with("Mulher")
  ) %>% 
  gt::cols_label(
    V2005 = "Condição no domicílio"
  )

table_perfil_2
  #gt::gt( row_group_as_column = TRUE)
```



```{r}
 table_perfil_3 <-
   dadosPNADc2025_DM_srv %>% 
  dplyr::group_by(V2007, V2005, V2010) %>% 
  dplyr::summarise(freq =  srvyr::survey_total(vartype = c("cv"))  ) %>% 
  gt::gt() %>%
  gt::tab_spanner(
    label = "Homem",
    columns = starts_with("Homem")
  ) %>%
  gt::tab_spanner(
    label = "Mulher",
    columns = starts_with("Mulher")
  ) %>% 
  gt::cols_label(
    V2005 = "Condição no domicílio",
    V2010 = "Cor ou Raça"
  )

table_perfil_3
  #gt::gt( row_group_as_column = TRUE)
```


```{r}
 table_perfil_5 <-
   dadosPNADc2025_DM_srv %>% 
  dplyr::group_by(V2007, V2001, V2005) %>% 
  dplyr::summarise(freq =  srvyr::survey_total(vartype = c("cv"))  ) %>% 
  gt::gt() %>%
  gt::tab_spanner(
    label = "Homem",
    columns = starts_with("Homem")
  ) %>%
  gt::tab_spanner(
    label = "Mulher",
    columns = starts_with("Mulher")
  ) %>% 
  gt::cols_label(
    V2001 = "Número de pessoas no domicílio",
    V2005 = "Condição no domicílio"
  )

table_perfil_5
  #gt::gt( row_group_as_column = TRUE)
```


### Educação



```{r}
 table_perfil_6 <-
   dadosPNADc2025_DM_srv %>% 
  dplyr::filter(V2009 >= 14) %>% 
  dplyr::group_by(V2007, V3001) %>% 
  dplyr::summarise(freq =  srvyr::survey_total(vartype = c("cv"))  ) %>% 
  gt::gt() %>%
  gt::tab_spanner(
    label = "Homem",
    columns = starts_with("Homem")
  ) %>%
  gt::tab_spanner(
    label = "Mulher",
    columns = starts_with("Mulher")
  ) %>% 
  gt::cols_label(
    V3001 = "Sabe ler e escrever"
  )

table_perfil_6
  #gt::gt( row_group_as_column = TRUE)
```


```{r}
 table_perfil_7 <-
   dadosPNADc2025_DM_srv %>% 
  dplyr::filter(V2009 >= 14) %>%
  dplyr::group_by(V2007, V3001, V2010) %>% 
  dplyr::summarise(freq =  srvyr::survey_total(vartype = c("cv"))  ) %>% 
  gt::gt() %>%
  gt::tab_spanner(
    label = "Homem",
    columns = starts_with("Homem")
  ) %>%
  gt::tab_spanner(
    label = "Mulher",
    columns = starts_with("Mulher")
  ) %>% 
  gt::cols_label(
    V3001 = "Sabe ler e escrever",
    V2010 = "Cor ou raça"
  )

table_perfil_7
  #gt::gt( row_group_as_column = TRUE)
```







```{r}
 table_perfil_8 <-
   dadosPNADc2025_DM_srv %>% 
  dplyr::filter(V2009 >= 14) %>%
  dplyr::group_by(V2007, V3009A, V2010) %>% 
  dplyr::summarise(freq =  srvyr::survey_total(vartype = c("cv"))  ) %>% 
  gt::gt() %>%
  gt::tab_spanner(
    label = "Homem",
    columns = starts_with("Homem")
  ) %>%
  gt::tab_spanner(
    label = "Mulher",
    columns = starts_with("Mulher")
  ) %>% 
  gt::cols_label(
    V3009A = "Qual foi o curso mais elevado que ... frequentou anteriormente?",
    V2010 = "Cor ou raça"
  )

table_perfil_8
  #gt::gt( row_group_as_column = TRUE)
```



```{r}
 table_perfil_9 <-
   dadosPNADc2025_DM_srv %>% 
  dplyr::group_by(V2007, V3009A) %>% 
  dplyr::summarise(freq =  srvyr::survey_total(vartype = c("cv"))  ) %>% 
  gt::gt() %>%
  gt::tab_spanner(
    label = "Homem",
    columns = starts_with("Homem")
  ) %>%
  gt::tab_spanner(
    label = "Mulher",
    columns = starts_with("Mulher")
  ) %>% 
  gt::cols_label(
    V3009A = "Qual foi o curso mais elevado que ... frequentou anteriormente?"
  )

table_perfil_9
  #gt::gt( row_group_as_column = TRUE)
```

```{r}
 table_perfil_9 <-
   dadosPNADc2025_DM_srv %>% 
  dplyr::group_by(V2007, V3009A) %>% 
  dplyr::summarise(freq =  srvyr::survey_total(vartype = c("cv"))  ) %>% 
  gt::gt() %>%
  gt::tab_spanner(
    label = "Homem",
    columns = starts_with("Homem")
  ) %>%
  gt::tab_spanner(
    label = "Mulher",
    columns = starts_with("Mulher")
  ) %>% 
  gt::cols_label(
    V3009A = "Qual foi o curso mais elevado que ... frequentou anteriormente?"
  )

table_perfil_9
  #gt::gt( row_group_as_column = TRUE)
```


### Trabalho

```{r}
 table_perfil_11 <-
   dadosPNADc2025_DM_srv %>% 
  dplyr::group_by(V2007, V3009A) %>% 
  dplyr::summarise(freq =  srvyr::survey_total(vartype = c("cv"))  ) %>% 
  gt::gt() %>%
  gt::tab_spanner(
    label = "Homem",
    columns = starts_with("Homem")
  ) %>%
  gt::tab_spanner(
    label = "Mulher",
    columns = starts_with("Mulher")
  ) %>% 
  gt::cols_label(
    V3009A = "Qual foi o curso mais elevado que ... frequentou anteriormente?"
  )

table_perfil_11
  #gt::gt( row_group_as_column = TRUE)
```




```{r}
dadosPNADc2025_DM_srv %>% 
  dplyr::filter(VD4002 == "Pessoas ocupadas") %>% 
  dplyr::group_by(V2007, V4012) %>% 
   dplyr::summarise(freq = srvyr::survey_total(vartype = c("se", "ci", "var", "cv")),
                    Qtd_renda = srvyr::survey_total(VD4017,
                                                   na.rm = TRUE))


dadosPNADc2025_DM_srv %>% 
  #dplyr::filter(VD4002 == "Pessoas ocupadas") %>% 
  dplyr::group_by(V2007, VD4030) %>% 
   dplyr::summarise(freq = srvyr::survey_total(vartype = c("se", "ci", "var", "cv")),
                    Qtd_renda = srvyr::survey_total(VD4017,
                                                   na.rm = TRUE))


  
```




```{r}


table_perfil_12 <-
   dadosPNADc2025_DM_srv %>% 
  dplyr::group_by(V2007, V4009) %>% 
  dplyr::summarise(freq =  srvyr::survey_total(vartype = c("cv"))  ) %>% 
  gt::gt() %>%
  gt::tab_spanner(
    label = "Homem",
    columns = starts_with("Homem")
  ) %>%
  gt::tab_spanner(
    label = "Mulher",
    columns = starts_with("Mulher")
  ) %>% 
  gt::cols_label(
    V4009 = "Quantos trabalhos ... tinha na semana de ... a ... (semana de referência ?"
  )

table_perfil_12

```



```{r}


table_perfil_13 <-
   dadosPNADc2025_DM_srv %>% 
  dplyr::group_by(V2007, V4009, V2010) %>% 
  dplyr::summarise(freq =  srvyr::survey_total(vartype = c("cv"))  ) %>% 
  gt::gt() %>%
  gt::tab_spanner(
    label = "Homem",
    columns = starts_with("Homem")
  ) %>%
  gt::tab_spanner(
    label = "Mulher",
    columns = starts_with("Mulher")
  ) %>% 
  gt::cols_label(
    V4009 = "Quantos trabalhos ... tinha na semana de ... a ... (semana de referência ?",
    V2010 = "Cor ou raça"
  )

table_perfil_13

```






### Renda


```{r}
table_perfil_14 <-
   dadosPNADc2025_DM_srv %>%
  dplyr::filter(VD4002 == "Pessoas ocupadas") %>%
  dplyr::filter(V2009 >= 14) %>% 
  dplyr::group_by(V2007, V2010, V4009) %>% 
  dplyr::summarise(freq =  srvyr::survey_total(vartype = c("cv")),
                   Qtd_horasHabituais = srvyr::survey_total(V4039,
                                                   na.rm = TRUE),
                   
                   Qtd_renda = srvyr::survey_total(VD4017,
                                                   na.rm = TRUE)) %>% 
  gt::gt() %>%
  gt::tab_spanner(
    label = "Homem",
    columns = starts_with("Homem")
  ) %>%
  gt::tab_spanner(
    label = "Mulher",
    columns = starts_with("Mulher")
  ) %>% 
  gt::cols_label(
    V4009 = "Quantos trabalhos ... tinha na semana de ... a ... (semana de referência ?",
    V2010 = "Cor ou raça"
  )

table_perfil_14

```

