---
title: "PNAD Contínua" # Título do relatório
subtitle: "**Baixar dados**"
author: "Fernanda Kelly R. Silva | www.fernandakellyrs.com"
lang: pt 
date: "`r format(Sys.Date())`" 
date-format: short 
toc: true 
format: 
    html: 
      embed-resources: true
      #css: ["custom.css"] 
      code-fold: false 
      code-tools: true  
      theme: 
        light: cosmo
        dark: superhero 
#title-block-banner: "#874a9c" 
code-annotations: hover 
execute:
  warning: false
  message: false
  echo: false
---


```{r}
#| echo: false
#| 
# install.packages("PNADcIBGE")
# install.packages("survey")
library(PNADcIBGE)
library(survey)
library(foreign)
library(srvyr)
library(reactable)
library(purrr)
library(furrr)
library(future)
```

# Trimestre

```{r}
# Vetor com os trimestres
trimestres <- 1:4

# Função para baixar os dados de cada trimestre
baixar_pnad <- function(t) {
  get_pnadc(year = 2012,
            quarter = t,
            #vars = c("UF", "V4039C", "VD4002", "V4013"),
            design = FALSE)
}

# Aplicando a função para todos os trimestres
dadosPNADc2012 <- map(trimestres, baixar_pnad)
# Nomeando cada elemento da lista
names(dadosPNADc2012) <- paste0("Trimestre_", trimestres)

dadosPNADc2012_completo <- dplyr::bind_rows(dadosPNADc2012, .id = "Trimestre")

```

```{r}
save(dadosPNADc2012_completo, file = "C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/dadosPNADc2012_completo.RData")
```


# Visitas

## 1

```{r}
future::plan(multisession, workers = 7)
```

### 2012 - 2015

```{r}

# Parâmetros ----
anos <- 2012:2015
visita <- 1

# Baixar PNAD Contínua em paralelo com barra de progresso ----
dadosPNADc1VISITA_12_15 <- future_map_dfr(
  anos,
  \(ano) {
    library(PNADcIBGE, quietly = TRUE)
    PNADcIBGE::get_pnadc(
      year = ano,
      interview = visita,
      design = FALSE
    ) 
  }
)

```

```{r}
save(dadosPNADc1VISITA_12_15, file = "C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Visitas/dadosPNADc1VISITA_12_15.RData")
```

### 2016 - 2019

```{r}

# Parâmetros ----
anos <- 2016:2019
visita <- 1

# Baixar PNAD Contínua em paralelo com barra de progresso ----
dadosPNADc1VISITA_16_19 <- future_map_dfr(
  anos,
  \(ano) {
    library(PNADcIBGE, quietly = TRUE)
    PNADcIBGE::get_pnadc(
      year = ano,
      interview = visita,
      design = FALSE
    ) 
  }
)

```

```{r}
save(dadosPNADc1VISITA_16_19, file = "C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Visitas/dadosPNADc1VISITA_16_19.RData")
```

### 2023 - 2024

```{r}

# Parâmetros ----
anos <- 2023:2024
visita <- 1

# Baixar PNAD Contínua em paralelo com barra de progresso ----
dadosPNADc1VISITA_23_24 <- future_map_dfr(
  anos,
  \(ano) {
    library(PNADcIBGE, quietly = TRUE)
    PNADcIBGE::get_pnadc(
      year = ano,
      interview = visita,
      design = FALSE
    ) 
  }
)

```

```{r}
save(dadosPNADc1VISITA_23_24, file = "C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Visitas/dadosPNADc1VISITA_23_24.RData")
```

### 2025

```{r}

dadosPNADc1VISITA_25_1 <- PNADcIBGE::get_pnadc(
      year = 2025,
      quarter = 1,
      design = FALSE
    ) 

dadosPNADc1VISITA_25_2 <- PNADcIBGE::get_pnadc(
      year = 2025,
      quarter = 2,
      design = FALSE
    )

```

```{r}
dadosPNADc1VISITA_25 <-  dadosPNADc1VISITA_25_1 %>% 
                         dplyr::bind_rows(dadosPNADc1VISITA_25_2)
```

```{r}
save(dadosPNADc1VISITA_25, file = "C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Trimestre/dadosPNADc1VISITA_25.RData")
```

## 5

### 2020 - 2022

```{r}
future::plan(multisession, workers = 7)
```

```{r}
anos <- 2020:2022

visita5_pnad <- furrr::future_map_dfr(
  anos,
  \(ano) {
    library(PNADcIBGE, quietly = TRUE)
    PNADcIBGE::get_pnadc(
      year = ano,
      interview = 5,
      design = FALSE
    ) 
  }
)

```

```{r}
save(visita5_pnad, file = "C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Visitas/dadosPNADc5VISITA_completo.RData")
```





















