---
title: "PNAD Contínua" # Título do relatório
subtitle: "**Demandas Rápidas**"
author: "Fernanda Kelly R. Silva | www.fernandakellyrs.com"
lang: pt 
date: "`r format(Sys.Date())`" 
date-format: short 
toc: true 
format: 
    html: 
      embed-resources: true
      #css: ["custom.css"] 
      code-fold: false 
      code-tools: true  
      theme: 
        light: cosmo
        dark: superhero 
#title-block-banner: "#874a9c" 
code-annotations: hover 
execute:
  warning: false
  message: false
  echo: false
---

```{r}
options(timeout = 600) 
options(scipen = 999)
```

```{r}
#| echo: false
#| 
# install.packages("PNADcIBGE")
# install.packages("survey")
library(PNADcIBGE)
library(survey)
library(foreign)
library(srvyr)
library(reactable)
library(purrr)
library(janitor)
library(gtsummary)
```

```{r}
load("C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Trimestre/dadosPNADc2023_completo.RData")
```

```{r}
dadosPNADc2023_RS <- dadosPNADc2023_completo %>% 
  dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas" & VD4002 == "Pessoas ocupadas") 
  #dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas" & Trimestre == 1) 

```

# Principal

```{r}

dadosPNADc2023_RS  <- PNADcIBGE::pnadc_design(dadosPNADc2023_RS)
dadosPNADc2023_RS_PSV <- srvyr::as_survey(dadosPNADc2023_RS)

table_P <- dadosPNADc2023_RS_PSV %>% 
  dplyr::mutate(VD4002 = base::as.numeric(VD4002)) %>% 
  dplyr::group_by(V4013) %>% 
  dplyr::summarise(N_P = srvyr::survey_total(VD4002 == 1, na.rm = TRUE))

```

```{r}
table_P <- survey::svyby(~VD4002 == "Pessoas ocupadas", ~V4013,
               design = dadosPNADc2023_RS_P,
               svytotal,
               na.rm = TRUE,
               vartype=c("se","cv","cvpct","var"))
```

## Demanda: Principal & Renda (2019-2024)

```{r}

load("C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Visitas/dadosPNADc1VISITA_2019.RData")

load("C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Visitas/dadosPNADc5VISITA_2020.RData")

load("C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Visitas/dadosPNADc5VISITA_2021.RData")

load("C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Visitas/dadosPNADc5VISITA_2022.RData")

load("C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Visitas/dadosPNADc1VISITA_2023.RData")

load("C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Visitas/dadosPNADc1VISITA_2024.RData")

```

```{r}

dadosPNADc1VISITA_2019  <- PNADcIBGE::pnadc_design(dadosPNADc1VISITA_2019)
dadosPNADc1VISITA_2019 <- srvyr::as_survey(dadosPNADc1VISITA_2019)

dadosPNADc1VISITA_2019 <- dadosPNADc1VISITA_2019 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>% 
  dplyr::filter(VD4002 == "Pessoas ocupadas") 

table_1P_2019 <- dadosPNADc1VISITA_2019 %>%  
  dplyr::group_by(V4013, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(vartype = c("se", "ci", "var", "cv")),
                   Qtd_horasHabituais = srvyr::survey_total(V4039,
                                                   na.rm = TRUE),
                   
                   Qtd_renda = srvyr::survey_total(VD4017,
                                                   na.rm = TRUE)
  )



```

```{r}
teste_2019 <- dadosPNADc1VISITA_2019 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>% 
  #dplyr::filter(VD4002 == "Pessoas ocupadas") %>% 
  dplyr::filter(V40331 == "Em dinheiro") %>% 
  dplyr::filter(V40332 == "Em produtos ou mercadorias") %>% 
  dplyr::filter(V2009 >= 014)  %>% 
   #dplyr::filter(V4009 == "Um" | V4009 == "Dois" | V4009 == "Três ou mais")
  dplyr::filter(V4009 == "Um")


table_teste_2019 <- dadosPNADc1VISITA_2019 %>%  
  #dplyr::group_by(V4013, Ano) %>% 
  dplyr::group_by(Ano) %>%
  dplyr::mutate(renda_nova = base::sum(V403412, V403422, na.rm = TRUE)) %>% 
  dplyr::summarise(freq = srvyr::survey_total(vartype = c("se", "ci", "var", "cv")),
                   Qtd_horasHabituais = srvyr::survey_total(V4039,
                                                   na.rm = TRUE),
                   
                   Qtd_renda = srvyr::survey_total(VD4017,
                                                   na.rm = TRUE),
                   
                   renda_2019 = srvyr::survey_total(renda_nova,
                                                   na.rm = TRUE),
                   
                   renda_todos = srvyr::survey_total(VD4020,
                                                   na.rm = TRUE)
  ) %>% 
  dplyr::select(Ano, Qtd_renda, renda_2019, renda_todos)




```

```{r}
dadosPNADc5VISITA_2020  <- PNADcIBGE::pnadc_design(dadosPNADc5VISITA_2020)
dadosPNADc5VISITA_2020 <- srvyr::as_survey(dadosPNADc5VISITA_2020)

dadosPNADc5VISITA_2020 <- dadosPNADc5VISITA_2020 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>% 
  dplyr::filter(VD4002 == "Pessoas ocupadas") 

table_1P_2020 <- dadosPNADc5VISITA_2020 %>%  
  dplyr::group_by(V4013, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(vartype = c("se", "ci", "var", "cv")),
                   Qtd_horasHabituais = srvyr::survey_total(V4039,
                                                   na.rm = TRUE),
                   
                   Qtd_renda = srvyr::survey_total(VD4017,
                                                   na.rm = TRUE)
  )


```

```{r}
dadosPNADc5VISITA_2021  <- PNADcIBGE::pnadc_design(dadosPNADc5VISITA_2021)
dadosPNADc5VISITA_2021 <- srvyr::as_survey(dadosPNADc5VISITA_2021)

dadosPNADc5VISITA_2021 <- dadosPNADc5VISITA_2021 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>% 
  dplyr::filter(VD4002 == "Pessoas ocupadas") 

table_1P_2021 <- dadosPNADc5VISITA_2021 %>%  
  dplyr::group_by(V4013, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(vartype = c("se", "ci", "var", "cv")),
                   Qtd_horasHabituais = srvyr::survey_total(V4039,
                                                   na.rm = TRUE),
                   
                   Qtd_renda = srvyr::survey_total(VD4017,
                                                   na.rm = TRUE)
  )

```


```{r}
dadosPNADc5VISITA_2022  <- PNADcIBGE::pnadc_design(dadosPNADc5VISITA_2022)
dadosPNADc5VISITA_2022 <- srvyr::as_survey(dadosPNADc5VISITA_2022)

dadosPNADc5VISITA_2022 <- dadosPNADc5VISITA_2022 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>% 
  dplyr::filter(VD4002 == "Pessoas ocupadas")

table_1P_2022 <- dadosPNADc5VISITA_2022 %>%  
  dplyr::group_by(V4013, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(vartype = c("se", "ci", "var", "cv")),
                   Qtd_horasHabituais = srvyr::survey_total(V4039,
                                                   na.rm = TRUE),
                   
                   Qtd_renda = srvyr::survey_total(VD4017,
                                                   na.rm = TRUE)
  )
```

```{r}
dadosPNADc1VISITA_2023  <- PNADcIBGE::pnadc_design(dadosPNADc1VISITA_2023)
dadosPNADc1VISITA_2023 <- srvyr::as_survey(dadosPNADc1VISITA_2023)

dadosPNADc1VISITA_2023 <- dadosPNADc1VISITA_2023 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>% 
  dplyr::filter(VD4002 == "Pessoas ocupadas")

table_1P_2023 <- dadosPNADc1VISITA_2023 %>%  
  dplyr::group_by(V4013, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(vartype = c("se", "ci", "var", "cv")),
                   Qtd_horasHabituais = srvyr::survey_total(V4039,
                                                   na.rm = TRUE),
                   
                   Qtd_renda = srvyr::survey_total(VD4017,
                                                   na.rm = TRUE)
  )
```


```{r}
dadosPNADc1VISITA_2024  <- PNADcIBGE::pnadc_design(dadosPNADc1VISITA_2024)
dadosPNADc1VISITA_2024 <- srvyr::as_survey(dadosPNADc1VISITA_2024)

dadosPNADc1VISITA_2024 <- dadosPNADc1VISITA_2024 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>% 
  dplyr::filter(VD4002 == "Pessoas ocupadas")

table_1P_2024 <- dadosPNADc1VISITA_2024 %>%  
  dplyr::group_by(V4013, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(vartype = c("se", "ci", "var", "cv")),
                   Qtd_horasHabituais = srvyr::survey_total(V4039,
                                                   na.rm = TRUE),
                   
                   Qtd_renda = srvyr::survey_total(VD4017,
                                                   na.rm = TRUE)
  )
```


```{r}

table_1P <- table_1P_2019 %>% 
  dplyr::bind_rows(table_1P_2020, table_1P_2021, table_1P_2022, table_1P_2023, table_1P_2024) %>% 
  dplyr::filter(!(is.na(V4013))) %>% 
  dplyr::select(V4013, Ano, freq, Qtd_horasHabituais, Qtd_renda)

```

## Demanda: Principal, Secundário & Renda (2019-2024)


```{r}
load("C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Visitas/dadosPNADc1VISITA_2012.RData")

load("C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Visitas/dadosPNADc1VISITA_2013.RData")

load("C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Visitas/dadosPNADc1VISITA_2014.RData")

load("C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Visitas/dadosPNADc1VISITA_2015.RData")

load("C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Visitas/dadosPNADc1VISITA_2016.RData")

load("C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Visitas/dadosPNADc1VISITA_2017.RData")

load("C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Visitas/dadosPNADc1VISITA_2018.RData")

load("C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Visitas/dadosPNADc1VISITA_2019.RData")

load("C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Visitas/dadosPNADc5VISITA_2020.RData")

load("C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Visitas/dadosPNADc5VISITA_2021.RData")

load("C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Visitas/dadosPNADc5VISITA_2022.RData")

load("C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Visitas/dadosPNADc1VISITA_2023.RData")

load("C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Visitas/dadosPNADc1VISITA_2024.RData")

```


```{r}

dadosPNADc1VISITA_2012  <- PNADcIBGE::pnadc_design(dadosPNADc1VISITA_2012)
dadosPNADc1VISITA_2012 <- srvyr::as_survey(dadosPNADc1VISITA_2012)

dadosPNADc1VISITA_2012 <- dadosPNADc1VISITA_2012 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>% 
   dplyr:::filter(VD4017 > 0)

table_1RP_2012 <- dadosPNADc1VISITA_2012 %>%  
  dplyr::group_by(V4013, V4012, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(),
                   Qtd_renda = srvyr::survey_total(VD4017,
                                                   na.rm = TRUE))

dadosPNADc1VISITA_2012 <- dadosPNADc1VISITA_2012 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>% 
   dplyr:::filter(V405112 > 0)

table_1RS_2012 <- dadosPNADc1VISITA_2012 %>%  
  dplyr::mutate(Qtd_renda = base::sum(VD4017, V405112, V405122, na.rm = TRUE)) %>% 
  dplyr::group_by(V4044, V4043, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(),
                   Qtd_renda = srvyr::survey_total(Qtd_renda,
                                                   na.rm = TRUE))

```

```{r}

dadosPNADc1VISITA_2013  <- PNADcIBGE::pnadc_design(dadosPNADc1VISITA_2013)
dadosPNADc1VISITA_2013 <- srvyr::as_survey(dadosPNADc1VISITA_2013)

dadosPNADc1VISITA_2013 <- dadosPNADc1VISITA_2013 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>% 
   dplyr:::filter(VD4017 > 0)

table_1RP_2013 <- dadosPNADc1VISITA_2013 %>%  
  dplyr::group_by(V4013, V4012, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(),
                   Qtd_renda = srvyr::survey_total(VD4017,
                                                   na.rm = TRUE))

dadosPNADc1VISITA_2013 <- dadosPNADc1VISITA_2013 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>% 
   dplyr:::filter(V405112 > 0)

table_1RS_2013 <- dadosPNADc1VISITA_2013 %>%  
  dplyr::mutate(Qtd_renda = base::sum(VD4017, V405112, V405122, na.rm = TRUE)) %>% 
  dplyr::group_by(V4044, V4043, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(),
                   Qtd_renda = srvyr::survey_total(Qtd_renda,
                                                   na.rm = TRUE))

```


```{r}

dadosPNADc1VISITA_2014  <- PNADcIBGE::pnadc_design(dadosPNADc1VISITA_2014)
dadosPNADc1VISITA_2014 <- srvyr::as_survey(dadosPNADc1VISITA_2014)

dadosPNADc1VISITA_2014 <- dadosPNADc1VISITA_2014 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>% 
   dplyr:::filter(VD4017 > 0)

table_1RP_2014 <- dadosPNADc1VISITA_2014 %>%  
  dplyr::group_by(V4013, V4012, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(),
                   Qtd_renda = srvyr::survey_total(VD4017,
                                                   na.rm = TRUE))

dadosPNADc1VISITA_2014 <- dadosPNADc1VISITA_2014 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>% 
   dplyr:::filter(V405112 > 0)

table_1RS_2014 <- dadosPNADc1VISITA_2014 %>%  
  dplyr::mutate(Qtd_renda = base::sum(VD4017, V405112, V405122, na.rm = TRUE)) %>% 
  dplyr::group_by(V4044, V4043, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(),
                   Qtd_renda = srvyr::survey_total(Qtd_renda,
                                                   na.rm = TRUE))

```


```{r}

dadosPNADc1VISITA_2015  <- PNADcIBGE::pnadc_design(dadosPNADc1VISITA_2015)
dadosPNADc1VISITA_2015 <- srvyr::as_survey(dadosPNADc1VISITA_2015)

dadosPNADc1VISITA_2015 <- dadosPNADc1VISITA_2015 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>% 
   dplyr:::filter(VD4017 > 0)

table_1RP_2015 <- dadosPNADc1VISITA_2015 %>%  
  dplyr::group_by(V4013, V4012, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(),
                   Qtd_renda = srvyr::survey_total(VD4017,
                                                   na.rm = TRUE))

dadosPNADc1VISITA_2015 <- dadosPNADc1VISITA_2015 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>% 
   dplyr:::filter(V405112 > 0)

table_1RS_2015 <- dadosPNADc1VISITA_2015 %>%  
  dplyr::mutate(Qtd_renda = base::sum(VD4017, V405112, V405122, na.rm = TRUE)) %>% 
  dplyr::group_by(V4044, V4043, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(),
                   Qtd_renda = srvyr::survey_total(Qtd_renda,
                                                   na.rm = TRUE))

```

```{r}

dadosPNADc1VISITA_2016  <- PNADcIBGE::pnadc_design(dadosPNADc1VISITA_2016)
dadosPNADc1VISITA_2016 <- srvyr::as_survey(dadosPNADc1VISITA_2016)

dadosPNADc1VISITA_2016 <- dadosPNADc1VISITA_2016 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>% 
   dplyr:::filter(VD4017 > 0)

table_1RP_2016 <- dadosPNADc1VISITA_2016 %>%  
  dplyr::group_by(V4013, V4012, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(),
                   Qtd_renda = srvyr::survey_total(VD4017,
                                                   na.rm = TRUE))

dadosPNADc1VISITA_2016 <- dadosPNADc1VISITA_2016 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>% 
   dplyr:::filter(V405112 > 0)

table_1RS_2016 <- dadosPNADc1VISITA_2016 %>%  
  dplyr::mutate(Qtd_renda = base::sum(VD4017, V405112, V405122, na.rm = TRUE)) %>% 
  dplyr::group_by(V4044, V4043, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(),
                   Qtd_renda = srvyr::survey_total(Qtd_renda,
                                                   na.rm = TRUE))
```

```{r}

dadosPNADc1VISITA_2017  <- PNADcIBGE::pnadc_design(dadosPNADc1VISITA_2017)
dadosPNADc1VISITA_2017 <- srvyr::as_survey(dadosPNADc1VISITA_2017)

dadosPNADc1VISITA_2017 <- dadosPNADc1VISITA_2017 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>% 
   dplyr:::filter(VD4017 > 0)

table_1RP_2017 <- dadosPNADc1VISITA_2017 %>%  
  dplyr::group_by(V4013, V4012, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(),
                   Qtd_renda = srvyr::survey_total(VD4017,
                                                   na.rm = TRUE))

dadosPNADc1VISITA_2017 <- dadosPNADc1VISITA_2017 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>% 
   dplyr:::filter(V405112 > 0)

table_1RS_2017 <- dadosPNADc1VISITA_2017 %>%  
  dplyr::mutate(Qtd_renda = base::sum(VD4017, V405112, V405122, na.rm = TRUE)) %>% 
  dplyr::group_by(V4044, V4043, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(),
                   Qtd_renda = srvyr::survey_total(Qtd_renda,
                                                   na.rm = TRUE))
```

```{r}

dadosPNADc1VISITA_2018  <- PNADcIBGE::pnadc_design(dadosPNADc1VISITA_2018)
dadosPNADc1VISITA_2018 <- srvyr::as_survey(dadosPNADc1VISITA_2018)

dadosPNADc1VISITA_2018 <- dadosPNADc1VISITA_2018 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>% 
   dplyr:::filter(VD4017 > 0)

table_1RP_2018 <- dadosPNADc1VISITA_2018 %>%  
  dplyr::group_by(V4013, V4012, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(),
                   Qtd_renda = srvyr::survey_total(VD4017,
                                                   na.rm = TRUE))

dadosPNADc1VISITA_2018 <- dadosPNADc1VISITA_2018 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>% 
   dplyr:::filter(V405112 > 0)

table_1RS_2018 <- dadosPNADc1VISITA_2018 %>%  
  dplyr::mutate(Qtd_renda = base::sum(VD4017, V405112, V405122, na.rm = TRUE)) %>% 
  dplyr::group_by(V4044, V4043, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(),
                   Qtd_renda = srvyr::survey_total(Qtd_renda,
                                                   na.rm = TRUE))

```

```{r}

dadosPNADc1VISITA_2019  <- PNADcIBGE::pnadc_design(dadosPNADc1VISITA_2019)
dadosPNADc1VISITA_2019 <- srvyr::as_survey(dadosPNADc1VISITA_2019)

dadosPNADc1VISITA_2019 <- dadosPNADc1VISITA_2019 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>% 
   dplyr:::filter(VD4017 > 0)

table_1RP_2019 <- dadosPNADc1VISITA_2019 %>%  
  dplyr::group_by(V4013, V4012, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(),
                   Qtd_renda = srvyr::survey_total(VD4017,
                                                   na.rm = TRUE))

dadosPNADc1VISITA_2019 <- dadosPNADc1VISITA_2019 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>% 
   dplyr:::filter(V405112 > 0)

table_1RS_2019 <- dadosPNADc1VISITA_2019 %>%  
  dplyr::mutate(Qtd_renda = base::sum(VD4017, V405112, V405122, na.rm = TRUE)) %>% 
  dplyr::group_by(V4044, V4043, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(),
                   Qtd_renda = srvyr::survey_total(Qtd_renda,
                                                   na.rm = TRUE))

```


```{r}
dadosPNADc5VISITA_2020  <- PNADcIBGE::pnadc_design(dadosPNADc5VISITA_2020)
dadosPNADc5VISITA_2020 <- srvyr::as_survey(dadosPNADc5VISITA_2020)

dadosPNADc5VISITA_2020 <- dadosPNADc5VISITA_2020 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>% 
   dplyr:::filter(VD4017 > 0)

table_1RP_2020 <- dadosPNADc5VISITA_2020 %>%  
  dplyr::group_by(V4013, V4012, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(),
                   Qtd_renda = srvyr::survey_total(VD4017,
                                                   na.rm = TRUE))

dadosPNADc5VISITA_2020 <- dadosPNADc5VISITA_2020 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>% 
   dplyr:::filter(V405112 > 0)

table_1RS_2020 <- dadosPNADc5VISITA_2020 %>%  
  dplyr::mutate(Qtd_renda = base::sum(VD4017, V405112, V405122, na.rm = TRUE)) %>% 
  dplyr::group_by(V4044, V4043, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(),
                   Qtd_renda = srvyr::survey_total(Qtd_renda,
                                                   na.rm = TRUE))
```

```{r}
dadosPNADc5VISITA_2021  <- PNADcIBGE::pnadc_design(dadosPNADc5VISITA_2021)
dadosPNADc5VISITA_2021 <- srvyr::as_survey(dadosPNADc5VISITA_2021)

dadosPNADc5VISITA_2021 <- dadosPNADc5VISITA_2021 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>% 
   dplyr:::filter(VD4017 > 0)

table_1RP_2021 <- dadosPNADc5VISITA_2021 %>%  
  dplyr::group_by(V4013, V4012, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(),
                   Qtd_renda = srvyr::survey_total(VD4017,
                                                   na.rm = TRUE))

dadosPNADc5VISITA_2021 <- dadosPNADc5VISITA_2021 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>% 
   dplyr:::filter(V405112 > 0)

table_1RS_2021 <- dadosPNADc5VISITA_2021 %>%  
  dplyr::mutate(Qtd_renda = base::sum(VD4017, V405112, V405122, na.rm = TRUE)) %>% 
  dplyr::group_by(V4044, V4043, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(),
                   Qtd_renda = srvyr::survey_total(Qtd_renda,
                                                   na.rm = TRUE))

```


```{r}
dadosPNADc5VISITA_2022  <- PNADcIBGE::pnadc_design(dadosPNADc5VISITA_2022)
dadosPNADc5VISITA_2022 <- srvyr::as_survey(dadosPNADc5VISITA_2022)

dadosPNADc5VISITA_2022 <- dadosPNADc5VISITA_2022 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>% 
   dplyr:::filter(VD4017 > 0)

table_1RP_2022 <- dadosPNADc5VISITA_2022 %>%  
  dplyr::group_by(V4013, V4012, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(),
                   Qtd_renda = srvyr::survey_total(VD4017,
                                                   na.rm = TRUE))

dadosPNADc5VISITA_2022 <- dadosPNADc5VISITA_2022 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>% 
   dplyr:::filter(V405112 > 0)

table_1RS_2022 <- dadosPNADc5VISITA_2022 %>%  
  dplyr::mutate(Qtd_renda = base::sum(VD4017, V405112, V405122, na.rm = TRUE)) %>% 
  dplyr::group_by(V4044, V4043, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(),
                   Qtd_renda = srvyr::survey_total(Qtd_renda,
                                                   na.rm = TRUE))
```

```{r}
dadosPNADc1VISITA_2023  <- PNADcIBGE::pnadc_design(dadosPNADc1VISITA_2023)
dadosPNADc1VISITA_2023 <- srvyr::as_survey(dadosPNADc1VISITA_2023)

dadosPNADc1VISITA_2023 <- dadosPNADc1VISITA_2023 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>% 
   dplyr:::filter(VD4017 > 0)

table_1RP_2023 <- dadosPNADc1VISITA_2023 %>%  
  dplyr::group_by(V4013, V4012, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(),
                   Qtd_renda = srvyr::survey_total(VD4017,
                                                   na.rm = TRUE))

dadosPNADc1VISITA_2023 <- dadosPNADc1VISITA_2023 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>% 
   dplyr:::filter(V405112 > 0)

table_1RS_2023 <- dadosPNADc1VISITA_2023 %>%  
  dplyr::mutate(Qtd_renda = base::sum(VD4017, V405112, V405122, na.rm = TRUE)) %>% 
  dplyr::group_by(V4044, V4043, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(),
                   Qtd_renda = srvyr::survey_total(Qtd_renda,
                                                   na.rm = TRUE))
```


```{r}
dadosPNADc1VISITA_2024  <- PNADcIBGE::pnadc_design(dadosPNADc1VISITA_2024)
dadosPNADc1VISITA_2024 <- srvyr::as_survey(dadosPNADc1VISITA_2024)

dadosPNADc1VISITA_2024 <- dadosPNADc1VISITA_2024 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>% 
   dplyr:::filter(VD4017 > 0)

table_1RP_2024 <- dadosPNADc1VISITA_2024 %>%  
  dplyr::group_by(V4013, V4012, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(),
                   Qtd_renda = srvyr::survey_total(VD4017,
                                                   na.rm = TRUE))

dadosPNADc1VISITA_2024 <- dadosPNADc1VISITA_2024 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>% 
   dplyr:::filter(V405112 > 0)

table_1RS_2024 <- dadosPNADc1VISITA_2024 %>%  
  dplyr::mutate(Qtd_renda = base::sum(VD4017, V405112, V405122, na.rm = TRUE)) %>% 
  dplyr::group_by(V4044, V4043, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(),
                   Qtd_renda = srvyr::survey_total(Qtd_renda,
                                                   na.rm = TRUE))
```


```{r}

table_1RP <- table_1RP_2012 %>% 
  dplyr::bind_rows(table_1RP_2013,
                   table_1RP_2014,
                   table_1RP_2015,
                   table_1RP_2016,
                   table_1RP_2017,
                   table_1RP_2018,
                   table_1RP_2019,
                   table_1RP_2020,
                   table_1RP_2021,
                   table_1RP_2022,
                   table_1RP_2023,
                   table_1RP_2024) 

table_1RS <- table_1RS_2012 %>% 
  dplyr::bind_rows(table_1RS_2013,
                   table_1RS_2014,
                   table_1RS_2015,
                   table_1RS_2016,
                   table_1RS_2017,
                   table_1RS_2018,
                   table_1RS_2019,
                   table_1RS_2020,
                   table_1RS_2021,
                   table_1RS_2022,
                   table_1RS_2023,
                   table_1RS_2024) %>% 
  dplyr::rename("V4013" = V4044,
                "V4012" = V4043)


table_RENDA_PS <- table_1RP %>% 
  dplyr::bind_rows(table_1RS) %>% 
  dplyr::rename("CNAE" = V4013,
                "OCUPACAO" = V4012) %>% 
  dplyr::group_by(CNAE, OCUPACAO, Ano) %>% 
  dplyr::summarise(freq_N = base::sum(freq),
                   Qtd_Renda = base::sum(Qtd_renda))
  


writexl::write_xlsx(table_RENDA_PS, 
           paste0("C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/PNAD_projetos/Dados/table_RendaM0_12_24_1.xlsx"))

```


## Demanda: Formal e Informal (2019)


```{r}
load(file = "C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Visitas/dadosPNADc1VISITA_2019.RData")
```

```{r}
dadosPNADc1VISITA_2019 <- dadosPNADc1VISITA_2019 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") %>%
  dplyr::filter(VD4002 == "Pessoas ocupadas") %>%
  
  dplyr::mutate(Trimestre = base::factor(Trimestre, levels = c("1", "2", "3", "4"))) %>%
  dplyr::mutate(cod_SCN_PR =  dplyr::case_when(V4013 %in% c("01101","01102","01103","01104","01105",
                                                            "01106","01107","01108","01109","01110",
                                                            "01111","01112","01113","01114","01115",
                                                            "01116","01117","01118","01119","01201",
                                                            "01202","01203","01204","01205","01206",
                                                            "01207","01208","01209","01401","01402",
                                                            "01500","01999","02000","03001","03002") ~ 1,

V4013 %in% c("05000","06000","07001","07002","08001",
             "08002","08009","09000") ~ 2,

V4013 %in% c("10010","10021","10022","10030","10091",
             "10092","10093","10099","11000","12000",
             "13001","13002","14001","14002","15011",
             "15012","15020","16001","16002","17001",
             "17002","18000","19010","19020","19030",
             "20010","20020","20090","21000","22010",
             "22020","23010","23091","23099","24001",
             "24002","24003","25001","25002","26010",
             "26020","26030","26041","26042","27010",
             "27090","28000","29001","29002","29003",
             "30010","30020","30030","30090","31000",
             "32001","32002","32003","32009","33001","33002") ~ 3,

V4013 %in% c("35010","35021","35022","36000","37000","38000","39000") ~ 4,

V4013 %in% c("41000","42000","43000") ~ 5,

V4013 %in% c("45010","45020","45030","45040","48010",
             "48020","48030","48041","48042","48050",
             "48060","48071","48072","48073","48074",
             "48075","48076","48077","48078","48079",
             "48080","48090","48100") ~ 6,

V4013 %in% c("49010","49030","49040","49090","50000",
             "51000","52010","52020","53001","53002") ~ 7,

V4013 %in% c("58000","59000","60001","60002","61000","62000","63000") ~ 8,

V4013 %in% c("64000","65000","66001","66002") ~ 9,

V4013 == "68000" ~ 10,

#######################################################
V4013 %in% c("55000","56011","56012","56020","69000",
"70000","71000","72000","73010","73020",
"74000","75000","77010","77020","78000",
"79000","80000","81011","81012","81020",
"82001","82002","82003","82009","90000",
"91000","92000","93011","93012","93020",
"94010","94020","94091","94099","95010",
"95030","96010","96020","96030","96090",
"97000") ~ 11,

V4012 == "Trabalhador doméstico" & V4013 %in% c("85011","85012","85013",
                                                "85014","85021","85029",
                                                "86001","86002","86003",
                                                "86004","86009","87000","88000") ~ 11,
V4012 == "Empregado do setor privado" & V4013 %in% c("85011","85012","85013",
                                                     "85014","85021","85029",
                                                     "86001","86002","86003",
                                                     "86004","86009","87000","88000") ~ 11,
V4012 == "Empregador" & V4013 %in% c("85011","85012","85013",
                                     "85014","85021","85029",
                                     "86001","86002","86003",
                                     "86004","86009","87000","88000") ~ 11,
V4012 == "Conta própria" & V4013 %in% c("85011","85012","85013",
                                        "85014","85021","85029",
                                        "86001","86002","86003",
                                        "86004","86009","87000","88000") ~ 11,
V4012 == "Trabalhador familiar não remunerado" & V4013 %in% c("85011","85012","85013",
                                                              "85014","85021","85029",
                                                              "86001","86002","86003",
                                                              "86004","86009","87000","88000") ~ 11,

########################################################

V4013 %in% c("84011","84012","84013","84014","84015","84016","84017","84020") ~ 12,

V4012 == "Militar do exército, da marinha, da aeronáutica, da polícia militar ou do corpo de bombeiros militar" & V4013 %in% c("85011","85012","85013",
                                                                                                                               "85014","85021","85029",
                                                                                                                               "86001","86002","86003",
                                                                                                                               "86004","86009","87000",
                                                                                                                               "88000") ~ 12,
V4012 == "Empregado do setor público (inclusive empresas de economia mista)" & V4013 %in% c("85011","85012","85013",
                                                                                            "85014","85021","85029",
                                                                                            "86001","86002","86003",
                                                                                            "86004","86009","87000","88000") ~ 12,

########################################################

V4013 %in% c("99000","00000") ~ 0,

.default = NA_integer_)
 )  %>% 
 
    dplyr::mutate(cod_SCN_SEC =  dplyr::case_when(V4044 %in% c(
"01101","01102","01103","01104","01105",
"01106","01107","01108","01109","01110",
"01111","01112","01113","01114","01115",
"01116","01117","01118","01119","01201",
"01202","01203","01204","01205","01206",
"01207","01208","01209","01401","01402",
"01500","01999","02000","03001","03002") ~ 1,

V4044 %in% c("05000","06000","07001","07002","08001","08002","08009","09000") ~ 2,

V4044 %in% c("10010","10021","10022","10030","10091",
             "10092","10093","10099","11000","12000",
             "13001","13002","14001","14002","15011",
             "15012","15020","16001","16002","17001",
             "17002","18000","19010","19020","19030",
             "20010","20020","20090","21000","22010",
             "22020","23010","23091","23099","24001",
             "24002","24003","25001","25002","26010",
             "26020","26030","26041","26042","27010",
             "27090","28000","29001","29002","29003",
             "30010","30020","30030","30090","31000",
             "32001","32002","32003","32009","33001","33002") ~ 3,

V4044 %in% c("35010","35021","35022","36000","37000","38000","39000") ~ 4,

V4044 %in% c("41000","42000","43000") ~ 5,

V4044 %in% c("45010","45020","45030","45040","48010",
             "48020","48030","48041","48042","48050",
             "48060","48071","48072","48073","48074",
             "48075","48076","48077","48078","48079",
             "48080","48090","48100") ~ 6,


V4044 %in% c("49010","49030","49040","49090","50000",
             "51000","52010","52020","53001","53002") ~ 7,

V4044 %in% c("58000","59000","60001","60002","61000","62000","63000") ~ 8,

V4044 %in% c("64000","65000","66001","66002") ~ 9,

V4044 == "68000" ~ 10,


###################################################################

V4044 %in% c(
"55000","56011","56012","56020","69000",
"70000","71000","72000","73010","73020",
"74000","75000","77010","77020","78000",
"79000","80000","81011","81012","81020",
"82001","82002","82003","82009","90000",
"91000","92000","93011","93012","93020",
"94010","94020","94091","94099","95010",
"95030","96010","96020","96030","96090",
"97000") ~ 11,



V4043 == "Trabalhador doméstico" & V4044 %in% c("85011","85012","85013",
                                                "85014","85021", "85029",
                                                "86001","86002","86003",
                                                "86004","86009","87000","88000") ~ 11,
V4043 == "Empregado do setor privado" & V4044 %in% c("85011","85012","85013",
                                                     "85014","85021", "85029",
                                                     "86001","86002","86003",
                                                     "86004","86009","87000","88000") ~ 11,
V4043 == "Empregador" & V4044 %in% c("85011","85012","85013",
                                     "85014","85021", "85029",
                                     "86001","86002","86003",
                                     "86004","86009","87000","88000") ~ 11,
V4043 == "Conta própria" & V4044 %in% c("85011","85012","85013",
                                        "85014","85021", "85029",
                                        "86001","86002","86003",
                                        "86004","86009","87000","88000") ~ 11,
V4043 == "Trabalhador não remunerado em ajuda a membro do domicílio ou parente" & V4044 %in% c("85011","85012","85013",
                                                                                               "85014","85021", "85029",
                                                                                               "86001","86002","86003",
                                                                                               "86004","86009","87000","88000") ~ 11,


####################################################################

V4044 %in% c("84011","84012","84013","84014","84015","84016","84017","84020") ~ 12,

V4043 == "Militar do exército, da marinha, da aeronáutica, da polícia militar ou do corpo de bombeiros militar" & V4044 %in% c("85011","85012","85013",
                                                                                                                               "85014","85021","85029",
                                                                                                                               "86001","86002","86003",
                                                                                                                               "86004","86009","87000",
                                                                                                                               "88000") ~ 12,
V4043 == "Empregado do setor público (inclusive empresas de economia mista)" & V4044 %in% c("85011","85012","85013",
                                                                                            "85014","85021","85029",
                                                                                            "86001","86002","86003",
                                                                                            "86004","86009","87000","88000") ~ 12,

########################################################

V4044 %in% c("99000","00000") ~ 0,

.default = NA_integer_)
 ) %>% 
  dplyr::mutate(SIT_PR = dplyr::case_when( (V4012 == "Trabalhador doméstico" & V4029 == "Sim") |
                                           (V4012 == "Empregado do setor privado" & V4029 == "Sim") |
                                           (V4012 == "Empregado do setor público (inclusive empresas de economia mista)" & V4029 == "Sim") |
                                            (V4012 == "Militar do exército, da marinha, da aeronáutica, da polícia militar ou do corpo de bombeiros militar") |
                                            (V4012 == "Empregador" & V4032 == "Sim") |
                                            (V4012 == "Conta própria" & V4032 == "Sim") ~ "Formal",
                                           
                                           
                                           (V4012 == "Trabalhador doméstico" & V4029 == "Não") |
                                           (V4012 == "Empregado do setor privado" & V4029 == "Não") |
                                           (V4012 == "Empregado do setor público (inclusive empresas de economia mista)" & V4029 == "Não") |
                                           (V4012 == "Empregador" & V4032 == "Não") |
                                           (V4012 == "Conta própria" & V4032 == "Não") |
                                           (V4012 == "Trabalhador familiar não remunerado")  ~ "Informal",
                                           
                                           .default = NA_character_),
                SIT_SEC = dplyr::case_when( (V4043 == "Trabalhador doméstico" & V4048 == "Sim") |
                                           (V4043 == "Empregado do setor privado" & V4048 == "Sim") |
                                           (V4043 == "Empregado do setor público (inclusive empresas de economia mista)" & V4048 == "Sim") |
                                            (V4043 == "Militar do exército, da marinha, da aeronáutica, da polícia militar ou do corpo de bombeiros militar") |
                                            (V4043 == "Empregador" & V4049 == "Sim") |
                                            (V4043 == "Conta própria" & V4049 == "Sim") ~ "Formal",
                                           
                                           
                                           (V4043 == "Trabalhador doméstico" & V4048 == "Não") |
                                           (V4043 == "Empregado do setor privado" & V4048 == "Não") |
                                           (V4043 == "Empregado do setor público (inclusive empresas de economia mista)" & V4048 == "Não") |
                                           (V4043 == "Empregador" & V4049 == "Não") |
                                           (V4043 == "Conta própria" & V4049 == "Não") |
                                           (V4043 == "Trabalhador familiar não remunerado")  ~ "Informal",
                                           
                                           .default = NA_character_)
                
                )
```

## Demanda: Dia da Mulher


```{r}
load(file = "C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Trimestre/dadosPNADc2024_completo.RData")

load(file = "C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Trimestre/dadosPNADc2025_completo.RData")
```

```{r}
dadosPNADc2025_DM <- dadosPNADc2025_completo %>% 
    dplyr::filter(UF == "Rio Grande do Sul")

dadosPNADc2025_DM_srv  <- PNADcIBGE::pnadc_design(dadosPNADc2025_DM)
dadosPNADc2025_DM_srv  <- srvyr::as_survey(dadosPNADc2025_DM_srv)
```

### Perfil

```{r}
# 
# table_perfil <-
#   dadosPNADc2025_DM_srv %>% 
#   #dplyr::select(V2005, V2010, V1022, V2007) %>% 
#   gtsummary::tbl_svysummary(
#     percent = "row",
#     include = c(V2010, V1022, V2007),
#     by = V2007
#   )
# 
# table_perfil <-
#   dadosPNADc2025_DM_srv %>% 
#   dplyr::group_by(V2005, V2010) %>% 
#   dplyr::summarise(freq = srvyr::survey_total(vartype = c("se", "ci", "var", "cv")))
# 
# table_perfil %>% 
#   gt::gt()

```

```{r}
 table_perfil_1 <-
   dadosPNADc2025_DM_srv %>% 
   #dplyr::select(V2005, V2010, V1022, V2007) %>% 
  dplyr::group_by(V2007) %>% 
  dplyr::summarise(freq =  srvyr::survey_total(vartype = c("cv"))  ) %>% 
  gt::gt() 

table_perfil_1
```

```{r}
 table_perfil_4 <-
   dadosPNADc2025_DM_srv %>% 
  dplyr::group_by(V2007, V1022) %>% 
  dplyr::summarise(freq =  srvyr::survey_total(vartype = c("cv"))  ) %>% 
  gt::gt() %>%
  gt::tab_spanner(
    label = "Homem",
    columns = starts_with("Homem")
  ) %>%
  gt::tab_spanner(
    label = "Mulher",
    columns = starts_with("Mulher")
  ) %>% 
  gt::cols_label(
    V1022 = "Situação do domicílio"
  )

table_perfil_4
  #gt::gt( row_group_as_column = TRUE)
```

```{r}
 table_perfil_2 <-
   dadosPNADc2025_DM_srv %>% 
  dplyr::group_by(V2007, V2005) %>% 
  dplyr::summarise(freq =  srvyr::survey_total(vartype = c("cv"))  ) %>% 
  gt::gt() %>%
  gt::tab_spanner(
    label = "Homem",
    columns = starts_with("Homem")
  ) %>%
  gt::tab_spanner(
    label = "Mulher",
    columns = starts_with("Mulher")
  ) %>% 
  gt::cols_label(
    V2005 = "Condição no domicílio"
  )

table_perfil_2
  #gt::gt( row_group_as_column = TRUE)
```



```{r}
 table_perfil_3 <-
   dadosPNADc2025_DM_srv %>% 
  dplyr::group_by(V2007, V2005, V2010) %>% 
  dplyr::summarise(freq =  srvyr::survey_total(vartype = c("cv"))  ) %>% 
  gt::gt() %>%
  gt::tab_spanner(
    label = "Homem",
    columns = starts_with("Homem")
  ) %>%
  gt::tab_spanner(
    label = "Mulher",
    columns = starts_with("Mulher")
  ) %>% 
  gt::cols_label(
    V2005 = "Condição no domicílio",
    V2010 = "Cor ou Raça"
  )

table_perfil_3
  #gt::gt( row_group_as_column = TRUE)
```


```{r}
 table_perfil_5 <-
   dadosPNADc2025_DM_srv %>% 
  dplyr::group_by(V2007, V2001, V2005) %>% 
  dplyr::summarise(freq =  srvyr::survey_total(vartype = c("cv"))  ) %>% 
  gt::gt() %>%
  gt::tab_spanner(
    label = "Homem",
    columns = starts_with("Homem")
  ) %>%
  gt::tab_spanner(
    label = "Mulher",
    columns = starts_with("Mulher")
  ) %>% 
  gt::cols_label(
    V2001 = "Número de pessoas no domicílio",
    V2005 = "Condição no domicílio"
  )

table_perfil_5
  #gt::gt( row_group_as_column = TRUE)
```


### Educação



```{r}
 table_perfil_6 <-
   dadosPNADc2025_DM_srv %>% 
  dplyr::group_by(V2007, V3001) %>% 
  dplyr::summarise(freq =  srvyr::survey_total(vartype = c("cv"))  ) %>% 
  gt::gt() %>%
  gt::tab_spanner(
    label = "Homem",
    columns = starts_with("Homem")
  ) %>%
  gt::tab_spanner(
    label = "Mulher",
    columns = starts_with("Mulher")
  ) %>% 
  gt::cols_label(
    V3001 = "Sabe ler e escrever"
  )

table_perfil_6
  #gt::gt( row_group_as_column = TRUE)
```


```{r}
 table_perfil_7 <-
   dadosPNADc2025_DM_srv %>% 
  dplyr::group_by(V2007, V3001, V2010) %>% 
  dplyr::summarise(freq =  srvyr::survey_total(vartype = c("cv"))  ) %>% 
  gt::gt() %>%
  gt::tab_spanner(
    label = "Homem",
    columns = starts_with("Homem")
  ) %>%
  gt::tab_spanner(
    label = "Mulher",
    columns = starts_with("Mulher")
  ) %>% 
  gt::cols_label(
    V3001 = "Sabe ler e escrever",
    V2010 = "Cor ou raça"
  )

table_perfil_7
  #gt::gt( row_group_as_column = TRUE)
```







```{r}
 table_perfil_8 <-
   dadosPNADc2025_DM_srv %>% 
  dplyr::group_by(V2007, V3009A) %>% 
  dplyr::summarise(freq =  srvyr::survey_total(vartype = c("cv"))  ) %>% 
  gt::gt() %>%
  gt::tab_spanner(
    label = "Homem",
    columns = starts_with("Homem")
  ) %>%
  gt::tab_spanner(
    label = "Mulher",
    columns = starts_with("Mulher")
  ) %>% 
  gt::cols_label(
    V3009A = "Qual foi o curso mais elevado que ... frequentou anteriormente?"
  )

table_perfil_8
  #gt::gt( row_group_as_column = TRUE)
```



```{r}
 table_perfil_9 <-
   dadosPNADc2025_DM_srv %>% 
  dplyr::group_by(V2007, V3009A) %>% 
  dplyr::summarise(freq =  srvyr::survey_total(vartype = c("cv"))  ) %>% 
  gt::gt() %>%
  gt::tab_spanner(
    label = "Homem",
    columns = starts_with("Homem")
  ) %>%
  gt::tab_spanner(
    label = "Mulher",
    columns = starts_with("Mulher")
  ) %>% 
  gt::cols_label(
    V3009A = "Qual foi o curso mais elevado que ... frequentou anteriormente?"
  )

table_perfil_9
  #gt::gt( row_group_as_column = TRUE)
```

```{r}
 table_perfil_9 <-
   dadosPNADc2025_DM_srv %>% 
  dplyr::group_by(V2007, V3009A) %>% 
  dplyr::summarise(freq =  srvyr::survey_total(vartype = c("cv"))  ) %>% 
  gt::gt() %>%
  gt::tab_spanner(
    label = "Homem",
    columns = starts_with("Homem")
  ) %>%
  gt::tab_spanner(
    label = "Mulher",
    columns = starts_with("Mulher")
  ) %>% 
  gt::cols_label(
    V3009A = "Qual foi o curso mais elevado que ... frequentou anteriormente?"
  )

table_perfil_9
  #gt::gt( row_group_as_column = TRUE)
```


### Trabalho

```{r}
 table_perfil_11 <-
   dadosPNADc2025_DM_srv %>% 
  dplyr::group_by(V2007, V3009A) %>% 
  dplyr::summarise(freq =  srvyr::survey_total(vartype = c("cv"))  ) %>% 
  gt::gt() %>%
  gt::tab_spanner(
    label = "Homem",
    columns = starts_with("Homem")
  ) %>%
  gt::tab_spanner(
    label = "Mulher",
    columns = starts_with("Mulher")
  ) %>% 
  gt::cols_label(
    V3009A = "Qual foi o curso mais elevado que ... frequentou anteriormente?"
  )

table_perfil_11
  #gt::gt( row_group_as_column = TRUE)
```




```{r}
dadosPNADc2025_DM_srv %>% 
  dplyr::filter(VD4002 == "Pessoas ocupadas") %>% 
  dplyr::group_by(V2007, V4012) %>% 
   dplyr::summarise(freq = srvyr::survey_total(vartype = c("se", "ci", "var", "cv")),
                    Qtd_renda = srvyr::survey_total(VD4017,
                                                   na.rm = TRUE))


dadosPNADc2025_DM_srv %>% 
  #dplyr::filter(VD4002 == "Pessoas ocupadas") %>% 
  dplyr::group_by(V2007, VD4030) %>% 
   dplyr::summarise(freq = srvyr::survey_total(vartype = c("se", "ci", "var", "cv")),
                    Qtd_renda = srvyr::survey_total(VD4017,
                                                   na.rm = TRUE))


  
```



















# Secundário 

```{r}

dadosPNADc2023_RS  <- PNADcIBGE::pnadc_design(dadosPNADc2023_RS)
dadosPNADc2023_RS_PSV <- srvyr::as_survey(dadosPNADc2023_RS)

table_S <- dadosPNADc2023_RS_PSV %>%                                           
  dplyr::mutate(VD4002 = base::as.numeric(VD4002)) %>%                                              
  dplyr::group_by(V4044) %>% 
  dplyr::summarise(N_S = srvyr::survey_total(VD4002 == 1, na.rm = TRUE))

```


```{r}
table_S <- survey::svyby(~VD4002 == "Pessoas ocupadas", ~V4044,
               design = dadosPNADc2023_RS_P,
               svytotal,
               na.rm = TRUE,
               vartype=c("se","cv","cvpct","var"))
```

# Principal & Secundário (2019-2024)

```{r}

load("C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Visitas/dadosPNADc1VISITA_2019.RData")

load("C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Visitas/dadosPNADc5VISITA_2020.RData")

load("C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Visitas/dadosPNADc5VISITA_2021.RData")

load("C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Visitas/dadosPNADc5VISITA_2022.RData")

load("C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Visitas/dadosPNADc1VISITA_2023.RData")

load("C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/Dados_completos/Visitas/dadosPNADc1VISITA_2024.RData")

```

## Demanda: Anos (2019-2024)

```{r}

dadosPNADc1VISITA_2019  <- PNADcIBGE::pnadc_design(dadosPNADc1VISITA_2019)
dadosPNADc1VISITA_2019 <- srvyr::as_survey(dadosPNADc1VISITA_2019)

dadosPNADc1VISITA_2019 <- dadosPNADc1VISITA_2019 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") 

table_1P_2019 <- dadosPNADc1VISITA_2019 %>%  
  dplyr::group_by(V4013, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(vartype = c("se", "ci", "var", "cv")))

table_1S_2019 <- dadosPNADc1VISITA_2019 %>%  
  dplyr::group_by(V4044, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(vartype = c("se", "ci", "var", "cv")))
```

```{r}
dadosPNADc5VISITA_2020  <- PNADcIBGE::pnadc_design(dadosPNADc5VISITA_2020)
dadosPNADc5VISITA_2020 <- srvyr::as_survey(dadosPNADc5VISITA_2020)

dadosPNADc5VISITA_2020 <- dadosPNADc5VISITA_2020 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") 

table_1P_2020 <- dadosPNADc5VISITA_2020 %>%  
  dplyr::group_by(V4013, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(vartype = c("se", "ci", "var", "cv")))

table_1S_2020 <- dadosPNADc5VISITA_2020 %>%  
  dplyr::group_by(V4044, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(vartype = c("se", "ci", "var", "cv")))
```

```{r}
dadosPNADc5VISITA_2021  <- PNADcIBGE::pnadc_design(dadosPNADc5VISITA_2021)
dadosPNADc5VISITA_2021 <- srvyr::as_survey(dadosPNADc5VISITA_2021)

dadosPNADc5VISITA_2021 <- dadosPNADc5VISITA_2021 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") 

table_1P_2021 <- dadosPNADc5VISITA_2021 %>%  
  dplyr::group_by(V4013, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(vartype = c("se", "ci", "var", "cv")))

table_1S_2021 <- dadosPNADc5VISITA_2021 %>%  
  dplyr::group_by(V4044, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(vartype = c("se", "ci", "var", "cv")))
```

```{r}
dadosPNADc5VISITA_2022  <- PNADcIBGE::pnadc_design(dadosPNADc5VISITA_2022)
dadosPNADc5VISITA_2022 <- srvyr::as_survey(dadosPNADc5VISITA_2022)

dadosPNADc5VISITA_2022 <- dadosPNADc5VISITA_2022 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") 

table_1P_2022 <- dadosPNADc5VISITA_2022 %>%  
  dplyr::group_by(V4013, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(vartype = c("se", "ci", "var", "cv")))

table_1S_2022 <- dadosPNADc5VISITA_2022 %>%  
  dplyr::group_by(V4044, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(vartype = c("se", "ci", "var", "cv")))
```

```{r}
dadosPNADc1VISITA_2023  <- PNADcIBGE::pnadc_design(dadosPNADc1VISITA_2023)
dadosPNADc1VISITA_2023 <- srvyr::as_survey(dadosPNADc1VISITA_2023)

dadosPNADc1VISITA_2023 <- dadosPNADc1VISITA_2023 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") 

table_1P_2023 <- dadosPNADc1VISITA_2023 %>%  
  dplyr::group_by(V4013, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(vartype = c("se", "ci", "var", "cv")))

table_1S_2023 <- dadosPNADc1VISITA_2023 %>%  
  dplyr::group_by(V4044, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(vartype = c("se", "ci", "var", "cv")))
```

```{r}
dadosPNADc1VISITA_2024  <- PNADcIBGE::pnadc_design(dadosPNADc1VISITA_2024)
dadosPNADc1VISITA_2024 <- srvyr::as_survey(dadosPNADc1VISITA_2024)

dadosPNADc1VISITA_2024 <- dadosPNADc1VISITA_2024 %>% 
    dplyr::filter(UF == "Rio Grande do Sul" & VD4002 == "Pessoas ocupadas") 

table_1P_2024 <- dadosPNADc1VISITA_2024 %>%  
  dplyr::group_by(V4013, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(vartype = c("se", "ci", "var", "cv")))

table_1S_2024 <- dadosPNADc1VISITA_2024 %>%  
  dplyr::group_by(V4044, Ano) %>% 
  dplyr::summarise(freq = srvyr::survey_total(vartype = c("se", "ci", "var", "cv")))
```

```{r}
table_1P <- table_1P_2019 %>% 
  dplyr::bind_rows(table_1P_2020, table_1P_2021, table_1P_2022, table_1P_2023, table_1P_2024) %>% 
  dplyr::filter(!(is.na(V4013))) %>% 
  dplyr::select(V4013, freq, Ano)

table_1S <- table_1S_2019 %>% 
  dplyr::bind_rows(table_1S_2020, table_1S_2021, table_1S_2022, table_1S_2023, table_1S_2024) %>% 
  dplyr::filter(!(is.na(V4044))) %>% 
  dplyr::select(V4044, freq, Ano)

table_PS_19_24 <- table_1P %>% 
  dplyr::left_join(table_1S, by = c("V4013" = "V4044", "Ano" = "Ano")) %>% 
  dplyr::group_by(V4013, Ano) %>% 
  dplyr::summarise(somaN = base::sum(freq.x, freq.y, na.rm = TRUE))

```



# Excel

```{r}
sheets <- list("PRINCIPAL"    = table_P,
               "SECUNDARIO"   = table_S)

writexl::write_xlsx(sheets, 
           paste0("C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/PNAD_projetos/Dados/tabPS2023_1.xlsx"))

#######################################
writexl::write_xlsx(table_PS_19_24, 
           paste0("C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/PNAD_projetos/Dados/table_PS_19_24_3.xlsx"))


#######################################
writexl::write_xlsx(table_1P, 
           paste0("C:/Users/fernanda-romeiro/OneDrive - Governo do Estado do Rio Grande do Sul/Projetos/PNAD/PNAD_projetos/Dados/tableRenda_P_19_24_1.xlsx"))
```



























